import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_colorpicker/flutter_colorpicker.dart';
import '../../../core/theme/app_theme.dart';
import '../../../domain/models/savings_goal.dart';
import '../providers/savings_goal_provider.dart';
import '../providers/auth_providers.dart';

class AddSavingsGoalSheet extends ConsumerStatefulWidget {
  final SavingsGoal? goal;

  const AddSavingsGoalSheet({super.key, this.goal});

  @override
  ConsumerState<AddSavingsGoalSheet> createState() =>
      _AddSavingsGoalSheetState();
}

class _AddSavingsGoalSheetState extends ConsumerState<AddSavingsGoalSheet> {
  final _formKey = GlobalKey<FormState>();
  late final TextEditingController _nameController;
  late final TextEditingController _targetController;
  late final TextEditingController _iconController;

  late Color _selectedColor;
  late bool _hasTarget;

  @override
  void initState() {
    super.initState();
    final goal = widget.goal;
    _nameController = TextEditingController(text: goal?.name ?? '');
    _targetController = TextEditingController(
      text: goal?.targetAmount?.toString() ?? '',
    );
    _iconController = TextEditingController(text: goal?.icon ?? '💰');
    _selectedColor = goal != null ? Color(goal.color) : Colors.green;
    _hasTarget = goal?.targetAmount != null;

    if (goal == null) {
      _hasTarget = true; // Default for new
    }
  }

  @override
  void dispose() {
    _nameController.dispose();
    _targetController.dispose();
    _iconController.dispose();
    super.dispose();
  }

  Future<void> _submit() async {
    if (_formKey.currentState!.validate()) {
      final groupId = await ref.read(currentGroupIdProvider.future);
      if (groupId == null) return;

      final targetAmount = _hasTarget
          ? double.tryParse(_targetController.text.replaceAll(',', '.'))
          : null;

      try {
        if (widget.goal != null) {
          // Update existing
          final updatedGoal = widget.goal!.copyWith(
            name: _nameController.text,
            icon: _iconController.text,
            targetAmount: targetAmount,
            color: _selectedColor.toARGB32(),
          );
          await ref
              .read(savingsGoalNotifierProvider.notifier)
              .updateSavingsGoal(updatedGoal);

          if (mounted) {
            Navigator.pop(context);
            ScaffoldMessenger.of(context).showSnackBar(
              const SnackBar(content: Text('Guardiola actualitzada!')),
            );
          }
        } else {
          // Create new
          final newGoal = SavingsGoal(
            id: '', // Generated by repo or ignored on add
            groupId: groupId,
            name: _nameController.text,
            icon: _iconController.text,
            currentAmount: 0.0,
            targetAmount: targetAmount,
            color: _selectedColor.toARGB32(),
            history: [],
          );
          await ref
              .read(savingsGoalNotifierProvider.notifier)
              .addSavingsGoal(newGoal);

          if (mounted) {
            Navigator.pop(context);
            ScaffoldMessenger.of(context).showSnackBar(
              const SnackBar(content: Text('Guardiola creada correctament!')),
            );
          }
        }
      } catch (e) {
        if (mounted) {
          ScaffoldMessenger.of(
            context,
          ).showSnackBar(SnackBar(content: Text('Error: $e')));
        }
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: EdgeInsets.only(
        bottom: MediaQuery.of(context).viewInsets.bottom,
        left: 16,
        right: 16,
        top: 16,
      ),
      child: Form(
        key: _formKey,
        child: SingleChildScrollView(
          child: Column(
            mainAxisSize: MainAxisSize.min,
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: [
              Text(
                widget.goal != null ? 'Editar Guardiola' : 'Nova Guardiola',
                style: Theme.of(context).textTheme.headlineSmall,
                textAlign: TextAlign.center,
              ),
              const SizedBox(height: 24),
              TextFormField(
                controller: _nameController,
                decoration: const InputDecoration(
                  labelText: 'Nom de l\'objectiu',
                  hintText: 'Ex: Viatge a Japó',
                  border: OutlineInputBorder(),
                ),
                textCapitalization: TextCapitalization.sentences,
                validator: (value) =>
                    value == null || value.isEmpty ? 'Introdueix un nom' : null,
              ),
              const SizedBox(height: 16),
              Row(
                children: [
                  Expanded(
                    child: TextFormField(
                      controller: _iconController,
                      decoration: const InputDecoration(
                        labelText: 'Icona (Emoji)',
                        border: OutlineInputBorder(),
                      ),
                      maxLength: 1,
                      textAlign: TextAlign.center,
                    ),
                  ),
                  const SizedBox(width: 16),
                  InkWell(
                    onTap: () {
                      showDialog(
                        context: context,
                        builder: (context) => AlertDialog(
                          title: const Text('Tria un color'),
                          content: SingleChildScrollView(
                            child: BlockPicker(
                              pickerColor: _selectedColor,
                              onColorChanged: (color) {
                                setState(() => _selectedColor = color);
                                Navigator.pop(context);
                              },
                            ),
                          ),
                        ),
                      );
                    },
                    child: Container(
                      width: 56,
                      height: 56,
                      decoration: BoxDecoration(
                        color: _selectedColor,
                        shape: BoxShape.circle,
                        border: Border.all(color: Colors.grey[300]!),
                      ),
                    ),
                  ),
                ],
              ),
              const SizedBox(height: 16),
              SwitchListTile(
                title: const Text('Té un import objectiu?'),
                value: _hasTarget,
                onChanged: (value) => setState(() => _hasTarget = value),
              ),
              if (_hasTarget)
                TextFormField(
                  controller: _targetController,
                  keyboardType: const TextInputType.numberWithOptions(
                    decimal: true,
                  ),
                  decoration: const InputDecoration(
                    labelText: 'Import Objectiu (€)',
                    border: OutlineInputBorder(),
                    prefixText: '€ ',
                  ),
                  validator: (value) {
                    if (!_hasTarget) return null;
                    if (value == null || value.isEmpty) {
                      return 'Introdueix un import';
                    }
                    if (double.tryParse(value.replaceAll(',', '.')) == null) {
                      return 'Import invàlid';
                    }
                    return null;
                  },
                ),
              const SizedBox(height: 24),
              ElevatedButton(
                onPressed: _submit,
                style: ElevatedButton.styleFrom(
                  backgroundColor: AppTheme.copper,
                  foregroundColor: Colors.white,
                  padding: const EdgeInsets.symmetric(vertical: 16),
                ),
                child: Text(
                  widget.goal != null ? 'Guardar Canvis' : 'Crear Guardiola',
                ),
              ),
              const SizedBox(height: 24),
            ],
          ),
        ),
      ),
    );
  }
}
