// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6RdZXD51rfHvB2rJ5nxOKZdO3GsAmpuk',
    appId: '1:823646138001:web:656f4261b139068e485930',
    messagingSenderId: '823646138001',
    projectId: 'centim-162bd',
    authDomain: 'centim-162bd.firebaseapp.com',
    storageBucket: 'centim-162bd.firebasestorage.app',
    measurementId: 'G-MFR2G7Y3SH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUem6LYMJYdqmsxBwgXiXvJZOj73qrUpQ',
    appId: '1:823646138001:android:68d9a062028f32ee485930',
    messagingSenderId: '823646138001',
    projectId: 'centim-162bd',
    storageBucket: 'centim-162bd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkFcE4GoYVH-J5gszTYBtTcRf2uRmid6E',
    appId: '1:823646138001:ios:55f3499d841347b6485930',
    messagingSenderId: '823646138001',
    projectId: 'centim-162bd',
    storageBucket: 'centim-162bd.firebasestorage.app',
    iosBundleId: 'com.example.centim',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkFcE4GoYVH-J5gszTYBtTcRf2uRmid6E',
    appId: '1:823646138001:ios:55f3499d841347b6485930',
    messagingSenderId: '823646138001',
    projectId: 'centim-162bd',
    storageBucket: 'centim-162bd.firebasestorage.app',
    iosBundleId: 'com.example.centim',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6RdZXD51rfHvB2rJ5nxOKZdO3GsAmpuk',
    appId: '1:823646138001:web:f9f4332baffa1ee0485930',
    messagingSenderId: '823646138001',
    projectId: 'centim-162bd',
    authDomain: 'centim-162bd.firebaseapp.com',
    storageBucket: 'centim-162bd.firebasestorage.app',
    measurementId: 'G-B1JGW577ZP',
  );
}
